name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/real-time-devops/app
            git pull origin main
            PID=$(pgrep -f "python3 app.py" || true)
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
            nohup python3 app.py > app.log 2>&1 &